kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 8081
      hostPort: 8081
      listenAddress: 127.0.0.1
    - containerPort: 50051
      hostPort: 50051
      listenAddress: 127.0.0.1
