apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.name }}"
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.image }}"
          ports:
            - name: "grpc"
              containerPort: 7777
      imagePullSecrets:
        - name: "pull-secret"
