apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ .Values.name }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.name }}"
spec:
  host: "{{ .Values.name }}"
  trafficPolicy:
    loadBalancer:
      # Supported load balancing options are as follows.
      #
      #     LEAST_CONN
      #     PASSTHROUGH
      #     RANDOM
      #     ROUND_ROBIN
      #
      # See also the istio reference.
      #
      #     https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB
      #
      simple: "LEAST_CONN"
