apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ .Values.name }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.name }}"
spec:
  host: "{{ .Values.name }}"
  trafficPolicy:
    loadBalancer:
      simple: "ROUND_ROBIN"
