apiVersion: "networking.istio.io/v1beta1"
kind: "Gateway"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  selector:
    istio: "ingressgateway"
  servers:
  - port:
      name: "grpc"
      number: {{ .Values.port }}
      protocol: "GRPC"
    hosts:
    - "*"
