apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.name }}"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "{{ .Values.name }}"
  ports:
    - name: "grpc"
      port: 7777
