apiVersion: "networking.istio.io/v1beta1"
kind: "VirtualService"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  hosts:
  - "*"
  gateways:
  - "{{ .Release.Name }}"
  http:
  - route:
    - destination:
        host: "{{ .Release.Name }}"
        port:
          number: {{ .Values.port }}
